# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('MachineTypeID', models.IntegerField()),
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('IdealTemperature', models.DateTimeField(verbose_name='date published')),
                ('IdealNoise', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
