# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0002_auto_20180220_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('MachineID', models.IntegerField(primary_key=True, serialize=False)),
                ('LastService', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Noise_Sensor_Data',
            fields=[
                ('RecordID', models.IntegerField(primary_key=True, serialize=False)),
                ('NoiseLogged', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateLogged', models.DateTimeField()),
                ('MachineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Sensor_Data',
            fields=[
                ('RecordID', models.IntegerField(primary_key=True, serialize=False)),
                ('TempLogged', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DateLogged', models.DateTimeField()),
                ('MachineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone.Machine')),
            ],
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='MachineTypeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='MachineTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone.MachineType'),
        ),
    ]
