# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0003_auto_20180302_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise_sensor_data',
            name='RecordID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temp_sensor_data',
            name='RecordID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
